import {
  ChainStat,
  FailurePoint,
  FounderChatInsight,
  ProtocolConfig,
  ProtocolMetrics,
  ProtocolNotification,
  SearchQueryItem,
  Timeframe,
  WalletUserItem,
} from "./types";

export const DEFAULT_CONFIG: ProtocolConfig = {
  botChainRpc: "https://rpc.botchain.ai",
  baseRpc: "https://mainnet.base.org",
  registryAddress: "0xb35788922a5b9C8938dE8AEDf725b88D26eEEa45",
  reownProjectId: "beccbc473190c8b06eb5471223604fdf",
  backendAnalyticsUrl: "https://qerin.vercel.app/api/analytics",
  refreshIntervalSec: 15,
  dailySpendCapUsd: 5.0,
};

export const INITIAL_METRICS: ProtocolMetrics = {
  totalRevenueUsd: 6.60,
  revenue24hUsd: 1.80,
  revenueChange24hPct: 37.5,
  totalQueries: 30,
  queries24h: 12,
  successfulListings: 30,
  walletsConnected: 3,
  totalUsers: 15,
  activeUsers: 12,
  agentSourceSpendUsd: 0.52,
  grossMarginPct: 92.1,
  avgLatencyMs: 1240,
  systemSuccessRatePct: 100.0,
};

export const INITIAL_NOTIFICATIONS: ProtocolNotification[] = [
  {
    id: "notif-1",
    title: "KPI 6 Verified On-Chain (14 Txs)",
    message: "14 transactions across 3 unique sender wallets confirmed on BOT Chain contract 0xb35788922a5b9c8938de8aedf725b88d26eeea45. All validator conditions verified 100%.",
    type: "milestone",
    timestamp: "10 mins ago",
    isRead: false,
    link: "https://scan.botchain.ai/address/0xb35788922a5b9c8938de8aedf725b88d26eeea45",
    linkText: "BOTScan Explorer",
    badge: "100% COMPLETE",
  },
  {
    id: "notif-2",
    title: "Grant Evaluation In Review",
    message: "Contract address and transaction telemetry submitted to Jainish (BOT Chain Ecosystem Growth Manager) for developer grant evaluation.",
    type: "grant",
    timestamp: "45 mins ago",
    isRead: false,
    badge: "ECOSYSTEM GRANT",
  },
  {
    id: "notif-3",
    title: "Spend Guard Normal ($0.52 / $5.00)",
    message: "Daily spend is only $0.52 of the $5.00 safety limit. Protocol net margin is 92.1% with $6.08 retained profit from $6.60 user inflow.",
    type: "guard",
    timestamp: "Live",
    isRead: true,
    badge: "92.1% MARGIN",
  },
  {
    id: "notif-4",
    title: "Zero Contract Reverts Record",
    message: "100% execution success across all 30 research queries. Zero smart contract reverts or dropped receipts recorded.",
    type: "system",
    timestamp: "Live",
    isRead: true,
    badge: "0 REVERTS",
  },
  {
    id: "notif-5",
    title: "Reown Web3 Cloud Connected",
    message: "Project ID beccbc473190c8b06eb5471223604fdf synced for multi-chain wallet authentication across 300+ Web3 wallets.",
    type: "web3",
    timestamp: "Active",
    isRead: true,
    badge: "REOWN CLOUD",
  },
];

export const INITIAL_FOUNDER_INSIGHTS: FounderChatInsight[] = [
  {
    id: "ins-1",
    topic: "BOT Chain Gas Subsidies & ERC-4337",
    userQuery: "What are the latest BOT Chain EVM gas subsidies and ERC-4337 bundler specs?",
    queryCount: 14,
    category: "EVM Gas",
    viralScore: 96,
    founderAction: "Write technical tutorial & post on X/Telegram about sub-cent gas execution.",
    draftPost: "Why we route 59.1% of @QerinProtocol research settlements to @BOTChainAI: $0.00008 avg gas vs $0.00065 on Base. In high-frequency autonomous AI agent loops, this 8x fee compression changes unit economics completely. 🤖⚡",
  },
  {
    id: "ins-2",
    topic: "DeepSeek R1 Economics & Distillation",
    userQuery: "Analyze DeepSeek R1 distillation techniques and token unit economics vs Claude 3.5 Sonnet",
    queryCount: 9,
    category: "AI & Infra",
    viralScore: 92,
    founderAction: "Publish benchmark teardown comparing local reasoning models with cloud frontier APIs.",
    draftPost: "What 12 crypto research accounts asked Qerin this week: Why DeepSeek R1 distillation changes autonomous agent economics forever compared to Claude 3.5 Sonnet. Here is the unit breakdown: 🧵👇",
  },
  {
    id: "ins-3",
    topic: "Llama 3.3 Latency & KV Cache Optimization",
    userQuery: "Llama 3.3 Latency & KV Cache Optimization for autonomous agent multi-step loops",
    queryCount: 4,
    category: "AI & Infra",
    viralScore: 84,
    founderAction: "Share NVIDIA NIM setup snippet for low-latency agent inference pipelines.",
    draftPost: "Optimizing NVIDIA NIM inference for autonomous research: Llama 3.3 KV cache tricks reduced our agent latency down to 980ms while retaining citation accuracy. 🏎️💨",
  },
  {
    id: "ins-4",
    topic: "x402 Cross-Chain Settlement Latency",
    userQuery: "Compare cross-chain settlement latency for x402 protocol across Base and Solana Devnet",
    queryCount: 2,
    category: "Cross-Chain",
    viralScore: 78,
    founderAction: "Publish latency comparison chart for multi-chain HTTP 402 payment headers.",
    draftPost: "Cross-chain AI micropayments benchmark: Base vs Solana vs BOT Chain. How x402 headers settle sub-cent research queries across L1 & L2 rails seamlessly. 🌐",
  },
  {
    id: "ins-5",
    topic: "ZK Proof Verification on Base L2",
    userQuery: "ZK Proof Verification cost curves and rollup compression benchmarks on Base L2",
    queryCount: 1,
    category: "DeFi",
    viralScore: 71,
    founderAction: "Detail rollup calldata costs for verifiable agent research attestation.",
    draftPost: "Rollup compression & ZK proof costs on Base: How autonomous agents can verify research integrity on-chain without prohibitive calldata overhead. 📊",
  },
];

export const INITIAL_CHAINS: ChainStat[] = [
  {
    name: "BOT Chain Mainnet",
    chainId: 677,
    symbol: "BOT",
    status: "active",
    totalTransactions: 26,
    txSharePct: 59.1,
    volumeUsd: 3.90,
    avgGasCostUsd: 0.00008,
    avgBlockTimeSec: 2.1,
    contractAddress: "0xb35788922a5b9C8938dE8AEDf725b88D26eEEa45",
    explorerUrl: "https://scan.botchain.ai",
    color: "#8b5cf6",
    isMaxChain: true,
  },
  {
    name: "Base Mainnet",
    chainId: 8453,
    symbol: "ETH",
    status: "active",
    totalTransactions: 16,
    txSharePct: 36.4,
    volumeUsd: 2.40,
    avgGasCostUsd: 0.00065,
    avgBlockTimeSec: 2.0,
    contractAddress: "0xb35788922a5b9C8938dE8AEDf725b88D26eEEa45",
    explorerUrl: "https://basescan.org",
    color: "#0052ff",
    isMaxChain: false,
  },
  {
    name: "Solana Devnet",
    chainId: 101,
    symbol: "SOL",
    status: "active",
    totalTransactions: 2,
    txSharePct: 4.5,
    volumeUsd: 0.30,
    avgGasCostUsd: 0.00025,
    avgBlockTimeSec: 0.4,
    contractAddress: "35hBqH...DevnetWallet",
    explorerUrl: "https://solscan.io",
    color: "#14f195",
    isMaxChain: false,
  },
];

export const INITIAL_QUERIES: SearchQueryItem[] = [
  {
    id: "q-1",
    query: "What are the latest BOT Chain EVM gas subsidies and ERC-4337 bundler specs?",
    topic: "BOT Chain Gas Subsidies & ERC-4337",
    category: "EVM Gas",
    sources: ["Superhighway", "BOT Chain Docs"],
    settlementStatus: "x402 Verified",
    amountUsd: 0.05,
    chain: "BOT Chain",
    txHash: "0xb228aaad1c0853f46fb4117c65f3ca25d1eaf15ebb95f9cf30c0b773d58e93a4",
    timestamp: "2 mins ago",
    latencyMs: 1180,
    userAddress: "0x11fa7869fd6fa3691a7df8dadd6a17326dee16c3",
  },
  {
    id: "q-2",
    query: "Analyze DeepSeek R1 distillation techniques and token unit economics vs Claude 3.5 Sonnet",
    topic: "DeepSeek R1 Economics & Distillation",
    category: "AI & Infra",
    sources: ["CryptoSlate Intelligence", "ArXiv / Semantic Scholar"],
    settlementStatus: "x402 Verified",
    amountUsd: 0.05,
    chain: "BOT Chain",
    txHash: "0x61a13cdd771edd9ac63553cbb616c521a55e6088dc49450e806df294d4bc88de",
    timestamp: "14 mins ago",
    latencyMs: 1420,
    userAddress: "0x5b2131e9b28a46ec10d260a14b9deb34554311f2",
  },
  {
    id: "q-3",
    query: "Llama 3.3 Latency & KV Cache Optimization for autonomous agent multi-step loops",
    topic: "Llama 3.3 Latency & KV Cache Optimization",
    category: "AI & Infra",
    sources: ["HuggingFace Papers", "NVIDIA NIM Docs"],
    settlementStatus: "x402 Verified",
    amountUsd: 0.03,
    chain: "BOT Chain",
    txHash: "0x20e3c3833220cd5cd8a7cb512e118665d744d37697d636b59f2177e453b3655e",
    timestamp: "32 mins ago",
    latencyMs: 980,
    userAddress: "0x5ad2ab59ad7fed120efc8160de64631c062d3495",
  },
  {
    id: "q-4",
    query: "Compare cross-chain settlement latency for x402 protocol across Base and Solana Devnet",
    topic: "x402 Cross-Chain Settlement Latency",
    category: "Cross-Chain",
    sources: ["Solana Docs", "Coinbase Developer Docs"],
    settlementStatus: "x402 Verified",
    amountUsd: 0.04,
    chain: "Base",
    txHash: "0x4d41c530014c1802347bbacf958114a60c19b58104a5365d2eae9043a8d834a5",
    timestamp: "1 hour ago",
    latencyMs: 1650,
    userAddress: "0x5ad2ab59ad7fed120efc8160de64631c062d3495",
  },
  {
    id: "q-5",
    query: "ZK Proof Verification cost curves and rollup compression benchmarks on Base L2",
    topic: "ZK Proof Verification on Base L2",
    category: "DeFi",
    sources: ["IACR ePrint", "Base Explorer"],
    settlementStatus: "x402 Verified",
    amountUsd: 0.04,
    chain: "Base",
    txHash: "0x082f62a11d24a089c1f7e8ff9d4cacc846556e547453032e7d2187a26bc12a3f",
    timestamp: "2 hours ago",
    latencyMs: 1310,
    userAddress: "0x11fa7869fd6fa3691a7df8dadd6a17326dee16c3",
  },
];

export const INITIAL_WALLETS: WalletUserItem[] = [
  {
    address: "0x5b2131e9b28a46ec10d260a14b9deb34554311f2",
    label: "Active Research Signer #1",
    queriesCount: 14,
    totalSpentUsd: 3.08,
    lastActive: "14 mins ago",
    type: "Active Research",
    primaryChain: "BOT Chain (677)",
  },
  {
    address: "0x5ad2ab59ad7fed120efc8160de64631c062d3495",
    label: "Active Research Signer #2",
    queriesCount: 10,
    totalSpentUsd: 2.20,
    lastActive: "32 mins ago",
    type: "Active Research",
    primaryChain: "BOT Chain (677) & Base (8453)",
  },
  {
    address: "0x11fa7869fd6fa3691a7df8dadd6a17326dee16c3",
    label: "On-Chain Registry Operator",
    queriesCount: 6,
    totalSpentUsd: 1.32,
    lastActive: "2 mins ago",
    type: "Operator",
    primaryChain: "BOT Chain (677)",
  },
];

export const INITIAL_FAILURES: FailurePoint[] = [
  {
    id: "f-1",
    category: "Spend Guard",
    description: "Automated cap halts queries if daily spending crosses configured limit ($5.00).",
    occurrences: 0,
    impact: "high",
    status: "mitigated",
    mitigation: "Strict Firestore transaction check runs before initiating x402 payment HTTP request.",
  },
  {
    id: "f-2",
    category: "Publisher Timeout",
    description: "External academic and research endpoints (e.g. Semantic Scholar) delaying response >5000ms.",
    occurrences: 2,
    impact: "medium",
    status: "monitoring",
    mitigation: "Fallback to Superhighway cache and secondary open web indices.",
  },
  {
    id: "f-3",
    category: "RPC Throttling",
    description: "Free public RPC rate limits causing temporary transaction receipt delays.",
    occurrences: 1,
    impact: "low",
    status: "resolved",
    mitigation: "Multi-RPC fallback array implemented for both BOT Chain and Base Mainnet.",
  },
  {
    id: "f-4",
    category: "Gas Variance",
    description: "Base L2 priority fee spikes during Ethereum mainnet gas surges.",
    occurrences: 0,
    impact: "low",
    status: "mitigated",
    mitigation: "Automatic routing to BOT Chain EVM which offers near-zero fixed gas fees ($0.00008).",
  },
];

export const TIMEFRAME_CHART_DATA: Record<
  Timeframe,
  { values: number[]; labels: string[]; changePct: number; changeDelta: number }
> = {
  "24H": {
    values: [4.80, 5.10, 5.05, 5.40, 5.85, 6.20, 6.42, 6.60],
    labels: ["00:00", "03:00", "06:00", "09:00", "12:00", "15:00", "18:00", "21:00"],
    changePct: 37.5,
    changeDelta: 1.80,
  },
  "7D": {
    values: [1.20, 2.10, 2.90, 3.80, 4.60, 5.80, 6.60],
    labels: ["Thu", "Fri", "Sat", "Sun", "Mon", "Tue", "Wed"],
    changePct: 450.0,
    changeDelta: 5.40,
  },
  "30D": {
    values: [0.15, 0.45, 0.90, 1.80, 2.70, 3.90, 5.10, 6.60],
    labels: ["W1", "W2", "W3", "W4"],
    changePct: 4300.0,
    changeDelta: 6.45,
  },
  ALL: {
    values: [0.00, 0.45, 1.20, 2.80, 4.40, 6.60],
    labels: ["Genesis", "Testnet", "Deploy", "Alpha", "Mainnet", "Current"],
    changePct: 660.0,
    changeDelta: 6.60,
  },
};
