// Base Mini App / Farcaster manifest. Served dynamically (rather than as a
// static public/ file) so it always reflects the real deployment URL instead
// of a hardcoded domain — required because the manifest's own homeUrl/iconUrl
// fields must match whatever domain gets registered and verified in the Base
// Build dashboard.
//
// accountAssociation must be generated by signing with the Farcaster/Base
// account that owns this app (via the Base Build dashboard's domain
// verification flow) — it cannot be produced from source code. Set
// BASE_ACCOUNT_ASSOCIATION_HEADER / _PAYLOAD / _SIGNATURE once that flow is
// complete; until then this manifest is served without it, which is enough
// for local development but not for the domain to verify.
export async function GET() {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  const accountAssociation =
    process.env.BASE_ACCOUNT_ASSOCIATION_HEADER &&
    process.env.BASE_ACCOUNT_ASSOCIATION_PAYLOAD &&
    process.env.BASE_ACCOUNT_ASSOCIATION_SIGNATURE
      ? {
          header: process.env.BASE_ACCOUNT_ASSOCIATION_HEADER,
          payload: process.env.BASE_ACCOUNT_ASSOCIATION_PAYLOAD,
          signature: process.env.BASE_ACCOUNT_ASSOCIATION_SIGNATURE,
        }
      : undefined;

  const appMeta = {
    version: "1",
    name: "Qerin",
    iconUrl: `${appUrl}/qerin-app-icon-square-1024.png`,
    homeUrl: appUrl,
    imageUrl: `${appUrl}/qerin-app-icon-1024.png`,
    buttonTitle: "Ask Qerin",
    splashImageUrl: `${appUrl}/qerin-app-icon-square-1024.png`,
    splashBackgroundColor: "#F7F5F0",
    subtitle: "Ask anything. Qerin pays for the truth.",
    description:
      "Qerin pays real x402 micropayments in USDC on Base to live publishers and data APIs, then returns a synthesized answer with an on-chain, verifiable receipt.",
    primaryCategory: "utility",
  };

  return Response.json({
    ...(accountAssociation ? { accountAssociation } : {}),
    // Both keys point at the same object: "frame" for clients still on the
    // older Farcaster Frames naming, "miniapp" for Base's current spec.
    frame: appMeta,
    miniapp: appMeta,
  });
}
