-- Baseline schema for the tables the backend already reads/writes on Neon
-- (apps/backend/src/accounts.ts, spendGuard.ts, apiKeys.ts). These tables
-- were originally provisioned by hand directly against the Neon project;
-- this migration formalizes that schema so new environments don't have to
-- guess it. Verified against the live production schema on 2026-08-15
-- (`psql "$DATABASE_URL" -c '\d <table>'`) rather than only inferred from
-- code — a few columns (api_keys.id/answer_requests.id as bigint identity,
-- answer_requests.api_key_id/billed_usd) exist in production but aren't
-- read/written by the current code; kept here so this file matches reality.
-- Do not rename columns without updating the code that reads/writes them.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  balance_usdc numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS api_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_hash text NOT NULL UNIQUE,
  key_prefix text NOT NULL,
  label text,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS deposits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id),
  -- Column name is a holdover from the original Coinbase Onramp
  -- integration; it now stores the Razorpay payment id (see
  -- apps/backend/src/razorpay.ts). Kept as-is to avoid a rename that
  -- would require touching accounts.ts's recordDeposit query.
  onramp_tx_id text NOT NULL UNIQUE,
  amount_usdc numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS answer_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Not written by current code (developer paywall answers don't record an
  -- api_key_id), but present in production; kept for schema fidelity.
  api_key_id bigint REFERENCES api_keys (id),
  source_cost_usd numeric(10, 4) NOT NULL,
  -- Not written by current code (spendGuard.ts's recordSpend never passes
  -- it); kept for schema fidelity, defaults to 0 like production.
  billed_usd numeric(10, 4) NOT NULL DEFAULT 0,
  source_count integer NOT NULL,
  user_id uuid REFERENCES users (id),
  debited_usd numeric,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deposits_user_id ON deposits (user_id);
CREATE INDEX IF NOT EXISTS idx_answer_requests_api_key_id ON answer_requests (api_key_id);
CREATE INDEX IF NOT EXISTS idx_answer_requests_user_id ON answer_requests (user_id);
-- Supports spendGuard.ts's daily-spend-cap query
-- (SUM(source_cost_usd) WHERE created_at >= date_trunc('day', now())).
CREATE INDEX IF NOT EXISTS idx_answer_requests_created_at ON answer_requests (created_at);
